// Generated by CoffeeScript 1.8.0
(function() {
  var $, Bacon, Bacon$, getServerTime, getTimeDiffProp, isTruthy, moment, timediff;

  $ = require('jquery');

  Bacon = require('baconjs');

  Bacon$ = require('bacon.jquery.ajax');

  moment = require('moment');

  timediff = function(one, the_other) {
    return moment(the_other).diff(one);
  };

  getServerTime = function(timeDiff) {
    return moment().utc().add(timeDiff);
  };

  isTruthy = function(item) {
    if (item) {
      return item;
    }
  };

  getTimeDiffProp = function(timeServerURL, updateTimeInterval) {
    var serverTimeResults, timeRequests;
    timeRequests = Bacon.interval(updateTimeInterval).map(function() {
      return {
        url: timeServerURL
      };
    });
    serverTimeResults = timeRequests.ajax().map(function(t) {
      return timediff(moment(t), moment());
    }).filter(isTruthy);
    return serverTimeResults.toProperty(null);
  };

  module.exports = getTimeDiffProp;

}).call(this);
